FROM langgenius/dify-api:1.14.2

USER root
WORKDIR /app/api
COPY --chown=dify:dify api/controllers/console/__init__.py /app/api/controllers/console/__init__.py
# 拷贝jk相关的代码
COPY --chown=dify:dify api/controllers/console/jk /app/api/controllers/console/jk
# 拷贝JK services代码
COPY --chown=dify:dify api/services/jk /app/api/services/jk
USER dify
